import ENERGY_PILL_IMAGE from './energyPillImage';
const EQUIP_ITEM_IMAGES: Record<string, any> = {
  pilula_energetica: ENERGY_PILL_IMAGE,
  brasao_coragem:   require('../assets/images/brasao-coragem.gif'),
  brasao_esperanca: require('../assets/images/brasao-esperanca.gif'),
  brasao_amizade:   require('../assets/images/brasao-amizade.gif'),
  brasao_confianca: require('../assets/images/brasao-confianca.gif'),
  brasao_pureza:    require('../assets/images/brasao-pureza.gif'),
  brasao_amor:      require('../assets/images/brasao-amor.gif'),
  brasao_luz:           require('../assets/images/brasao-luz.gif'),
  digivice_d2:             require('../assets/images/digivice_d2.webp'),
  digivice_d3:             require('../assets/images/digivice_d3.png'),
  digivice_d_ark:          require('../assets/images/digivice_d_ark.png'),
  digivice_xros_loader:    require('../assets/images/digivice_xros_loader.png'),
  oculos_escuro_fitado:    require('../assets/images/oculos_escuro_fitado.webp'),
  brasao_conhecimento:  require('../assets/images/brasao-conhecimento.gif'),
  brasao_bondade:       require('../assets/images/brasao-bondade.gif'),
  brasao_milagre:       require('../assets/images/braso-milagre.gif'),
  brasao_destino:       require('../assets/images/brasao-destino.gif'),
  pulseira_ouro:        require('../assets/images/pulseira_ouro.webp'),
  anel_sagrado:         require('../assets/images/anel_sagrado.webp'),
  piece_anel_sagrado:   require('../assets/images/anel_sagrado.webp'),
  piece_agulha:         require('../assets/images/agulha-media.webp'),
  piece_tecido:         require('../assets/images/tecido-arco-iris.webp'),
  piece_linha:          require('../assets/images/linha-arco-iris.webp'),
  piece_coragem:        require('../assets/images/coragem piece.png'),
  piece_brasao_bondade:      require('../assets/images/bondade piece.png'),
  piece_brasao_coragem:      require('../assets/images/coragem piece.png'),
  piece_brasao_esperanca:    require('../assets/images/esperança piece.png'),
  piece_brasao_amizade:      require('../assets/images/amizade piece.png'),
  piece_brasao_confianca:    require('../assets/images/confiança piece.png'),
  piece_brasao_pureza:       require('../assets/images/sinceridade piece.png'),
  piece_brasao_amor:         require('../assets/images/amor piece.png'),
  piece_brasao_luz:          require('../assets/images/luz piece.png'),
  piece_brasao_conhecimento: require('../assets/images/conhecimento piece.png'),
  piece_brasao_milagre:      require('../assets/images/milagre piece.png'),
  piece_brasao_destino:      require('../assets/images/destino piece.png'),
  piece_digivice_d3:          require('../assets/images/piece_digivice_d3.png'),
  piece_digivice_d_ark:       require('../assets/images/piece_digivice_d_ark.png'),
  piece_digivice_xros_loader: require('../assets/images/piece_digivice_xros_loader.png'),
  piece_battery_green:  require('../assets/images/battery_green.webp'),
  piece_battery_blue:   require('../assets/images/battery_blue.webp'),
  piece_battery_purple: require('../assets/images/battery_purple.webp'),
  piece_battery_gold:   require('../assets/images/battery_gold.webp'),
  blusa_social:     require('../assets/images/blusa_social.webp'),
  bermuda_poliester: require('../assets/images/bermuda_poliester.webp'),
  tenis_corrida:    require('../assets/images/tenis_corrida.webp'),
  gehenna:              require('../assets/images/gehenna.webp'),
  piece_gehenna:        require('../assets/images/gehenna.webp'),
  permissao_real:       require('../assets/images/permissao_real.webp'),
  black_digitron:       require('../assets/images/items/black_digitron.webp'),
  piece_black_digitron: require('../assets/images/items/black_digitron.webp'),
  x_antibody:           require('../assets/images/items/x_antibody.webp'),
  piece_x_antibody:     require('../assets/images/piece_x_antibody.gif'),
  piece_golden_ascension_star: require('../assets/images/items/golden_star_fragment.gif'),
  // Oásis do Olimpo — Papers
  piece_paper_apollomon: require('../assets/images/apollomon paper.png'),
  piece_paper_bacchusmon: require('../assets/images/Bacchusmon paper.png'),
  piece_paper_ceresmon: require('../assets/images/ceresmon paper.png'),
  piece_paper_dianamon: require('../assets/images/dianamon paper.png'),
  piece_paper_junomon: require('../assets/images/jonomon paper.png'),
  piece_paper_jupitermon: require('../assets/images/juptermon paper.png'),
  piece_paper_mercurymon: require('../assets/images/merukimon paper.png'),
  piece_paper_minervamon: require('../assets/images/minervamon paper.png'),
  piece_paper_neptunemon: require('../assets/images/neputnemon paper.png'),
  piece_paper_venusmon: require('../assets/images/venusmon paper.png'),
  piece_paper_vulcanusmon: require('../assets/images/vulcanusmon paper.png'),
  piece_paper_plutomon: require('../assets/images/plutomon paper.png'),

  // Cards
  card_aero_wing: require('../assets/images/Aero Wing.webp'),
  card_asas_brancas: require('../assets/images/Asas Brancas.webp'),
  card_battle_tomahawk: require('../assets/images/Battle Tomahawk.webp'),
  card_boost_chip: require('../assets/images/Boost Chip.webp'),
  card_broca_aco: require('../assets/images/Broca de Aço.webp'),
  card_devil_chip: require('../assets/images/Devil Chip.webp'),
  card_heavy_metal: require('../assets/images/Heavy Metal.webp'),
  card_king_device: require('../assets/images/King Device.webp'),
  card_knight_device: require('../assets/images/Knight Device.webp'),
  card_alta_velocidade_d: require('../assets/images/Plug-In de Alta Velocidade D.webp'),
  card_alta_velocidade_h: require('../assets/images/Plug-In de Alta Velocidade H.webp'),
  card_alta_velocidade_t: require('../assets/images/Plug-In de Alta Velocidade T.webp'),
  card_ataque_a: require('../assets/images/Plug-In de Ataque A.webp'),
  card_defesa_g: require('../assets/images/Plug-In de Defesa G.webp'),
  card_forca_o: require('../assets/images/Plug-In de Força O.webp'),
  card_forca_w: require('../assets/images/Plug-In de Força W.webp'),
  card_invalidacao_p: require('../assets/images/Plug-In de Invalidação P.webp'),
  card_recarregamento_q: require('../assets/images/Plug-In de Recarregamento Q.webp'),
  card_super_evolucao_s: require('../assets/images/Plug-In de Super Evolução S.webp'),
  card_power_charger: require('../assets/images/Power Charger.webp'),
  card_queen_device: require('../assets/images/Queen Device.webp'),
  card_semente_durabilidade: require('../assets/images/Semente da Durabilidade.webp'),
  card_st_51: require('../assets/images/St-51_2.webp'),
  card_st_382: require('../assets/images/St-382_2.webp'),
  card_st_384: require('../assets/images/St-384_2.webp'),
  card_thor_hammer: require('../assets/images/Thor Hammer.webp'),
  card_training_grips: require('../assets/images/Training Grips.webp'),
  card_universo_expansao: require('../assets/images/Universo em Expansão!.webp'),
  card_blue_caseira: require('../assets/images/Blue Card Caseira.webp'),
  card_blue: require('../assets/images/Blue Card.webp'),
  card_red: require('../assets/images/Red Card.webp'),

};

const DIGIVICE_IMAGES: Record<string, Record<string, any>> = {
  digivice_d2: {
    tamer_tai: require('../assets/images/d_2_orange.png'), tamer_matt: require('../assets/images/d_2_blue.png'),
    tamer_tk: require('../assets/images/d_2_yelow.png'), tamer_kari: require('../assets/images/d_2_pink.png'),
    tamer_sora: require('../assets/images/d_2_red.png'), tamer_mimi: require('../assets/images/d_2_green.png'),
  },
  digivice_d3: {
    tamer_tai: require('../assets/images/d_3_orange.png'), tamer_matt: require('../assets/images/d_3_blue.png'),
    tamer_tk: require('../assets/images/d_3_yelow.png'), tamer_kari: require('../assets/images/d_3_pink.png'),
    tamer_sora: require('../assets/images/d_3_red.png'), tamer_mimi: require('../assets/images/d_3_green.png'),
  },
  digivice_d_ark: {
    tamer_tai: require('../assets/images/d_ark_orange.png'), tamer_matt: require('../assets/images/d_ark_blue.png'),
    tamer_tk: require('../assets/images/yelow.png'), tamer_kari: require('../assets/images/d_ark_pink.png'),
    tamer_sora: require('../assets/images/d_ark_red.png'), tamer_mimi: require('../assets/images/d_ark_green.png'),
  },
  digivice_xros_loader: {
    tamer_tai: require('../assets/images/Xros_Loader_orange.png'), tamer_matt: require('../assets/images/Xros_Loader_blue.png'),
    tamer_tk: require('../assets/images/Xros_Loader_yelow.png'), tamer_kari: require('../assets/images/Xros_Loader_pink.png'),
    tamer_sora: require('../assets/images/Xros_Loader_red.png'), tamer_mimi: require('../assets/images/Xros_Loader_green.png'),
  },
};

export function getEquipItemImage(itemId: string, tamerId?: string | null): any {
  if (tamerId && DIGIVICE_IMAGES[itemId]?.[tamerId]) return DIGIVICE_IMAGES[itemId][tamerId];
  return EQUIP_ITEM_IMAGES[itemId];
}

export default EQUIP_ITEM_IMAGES;
